### ISSUE TITLE
Consider reusing a detective or precinct

### ISSUE THREAD

**Issue by mrjoelkemp** [mattpowell/gulp-haschanged-deps#1]
Regarding your comment about supporting AMD and aliasing, check out the following to see if any fit your needs:
- Precinct: https://github.com/mrjoelkemp/node-precinct
- Detective-AMD: https://github.com/mrjoelkemp/node-detective-amd
- Filing-cabinet: https://github.com/mrjoelkemp/node-filing-cabinet

Happy to answer any questions you might have.

Cheers,
Joel

**Comment by mattpowell** [comment]
Wow, can't believe it's October already. Anyways, was finally able to give this module some TLC!

I've incorporated Precinct (awesome library, btw) in commit 77deb7b538e06e6b3e499b0a2ac6331fb84b7565 , so, will close this issue, but definitely let me know if you have any other suggestions or ideas.

Thanks!

**Comment by mrjoelkemp** [comment]
Awesome! Thanks!
